--- #YAML:1.0
name                : pgsi
version             : 1.5.0
abstract            : Postgres system impact report
author:              
  - Mark Johnson <mark@endpoint.com>

license             : bsd
dynamic_config      : 1
distribution_type   : module

requires:
  IO::Handle        : 1.24
build_requires:
  Test::Harness     : 2.03
  Test::More        : 0.61
  Module::Signature : 0.50

provides:
  pgsi:
    file            : pgsi.pl
    version         : 1.5.0

resources:
  homepage          : http://bucardo.org/pgsi/index.html
  bugtracker        : http://bucardo.org/pgsi/bugs.html
  repository        : http://bucardo.org/pgsi/repo.html
  license           : http://bucardo.org/pgsi/license.txt
meta-spec:
  version           : 1.3
  url               : http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by        : emacs
